use std::collections::HashMap;

use anyhow::{Result, anyhow, bail};
mod control_flow;
mod fpu;
mod math;
mod misc;
mod mmx;
mod string;

use crate::{Block, BlockType, Instr, Module, State, memory::Memory, write_if_changed};

/// Preamble shared by the generated module and its parts.
const HEADER: &str = "//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use runtime::*;
";

/// Preamble for a part file: everything the module file has in scope,
/// including its sibling parts, reaches it through `super`.
const PART_HEADER: &str = "//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use super::*;
";

fn reg_name(r: iced_x86::Register) -> String {
    format!("{r:?}").to_ascii_lowercase()
}

fn instr_name(instr: &iced_x86::Instruction) -> String {
    if instr.mnemonic() == iced_x86::Mnemonic::Loop {
        return "loop_".to_string();
    }
    format!("{:?}", instr.mnemonic()).to_ascii_lowercase()
}

pub fn get_reg(r: iced_x86::Register) -> String {
    use iced_x86::Register::*;
    match r {
        EAX | ECX | EDX | EBX | ESI | EDI | ESP | EBP => {
            format!("ctx.cpu.regs.{reg}", reg = reg_name(r))
        }
        AL | AH | AX | CL | CH | CX | DL | DH | DX | BL | BH | BX |
        DI | SI | SP | BP | // comment to disable formatting
        CS | DS | ES | FS | GS | SS => {
            format!("ctx.cpu.regs.get_{reg}()", reg = reg_name(r))
        }
        r => todo!("{r:?}"),
    }
}

pub fn set_reg(r: iced_x86::Register, expr: String) -> String {
    use iced_x86::Register::*;
    match r {
        EAX | ECX | EDX | EBX | ESI | EDI | ESP | EBP => {
            format!("ctx.cpu.regs.{reg} = {expr};", reg = reg_name(r))
        }
        AL | AH | AX | CL | CH | CX | DL | DH | DX | BL | BH | BX |
        DI | SI | SP | BP | // comment to disable formatting
        CS | DS | ES | FS | GS | SS => {
            format!("ctx.cpu.regs.set_{reg}({expr});", reg = reg_name(r))
        }
        r => todo!("{r:?}"),
    }
}

impl<'a> CodeGen<'a> {
    /// Code generate a memory address reference.
    pub fn gen_addr_offset(&self, instr: &iced_x86::Instruction) -> String {
        use iced_x86::Register::*;
        let mut expr = Vec::new();
        if !self.module.segment_addressed() {
            // 16-bit segments handled in gen_addr(), not here
            match instr.memory_segment() {
                CS | DS | ES | GS | SS => {}
                FS => expr.push(format!("ctx.cpu.regs.fs_base")),
                None => {}
                r => todo!("{r:?} in {instr}"),
            }
        }
        match instr.memory_base() {
            None => {}
            r => expr.push(get_reg(r)),
        }
        if instr.memory_index() != None {
            if instr.memory_index_scale() != 1 {
                expr.push(format!(
                    "({}*{})",
                    get_reg(instr.memory_index()),
                    instr.memory_index_scale()
                ));
            } else {
                expr.push(format!("{}", get_reg(instr.memory_index()),));
            }
        }
        let offset = instr.memory_displacement32();
        if offset != 0 || expr.is_empty() {
            expr.push(format!("{offset:#x}u{}", self.module.bitness()));
        }

        expr.into_iter()
            .enumerate()
            .map(|(i, e)| {
                if i == 0 {
                    format!("{e}")
                } else {
                    format!(".wrapping_add({e})")
                }
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// Codegen the absolute address found in an instruction that has a memory reference.
    /// Even for 16-bit code we generate a 32-bit memory address, because the computed
    /// address can go beyond a 16-bit address range.
    pub fn gen_addr(&self, instr: &iced_x86::Instruction) -> String {
        let addr = self.gen_addr_offset(instr);
        if self.module.segment_addressed() {
            // The above offset expression will be a u16 in real mode.
            // Convert to u32 as we add the segment.
            format!(
                "segofs(ctx.cpu.regs.get_{seg}(), {addr})",
                seg = reg_name(instr.memory_segment())
            )
        } else {
            addr
        }
    }
}

pub fn get_mem(typ: String, addr: String) -> String {
    format!("ctx.memory.read::<{typ}>({addr})")
}

pub fn set_mem(typ: String, addr: String, expr: String) -> String {
    format!("ctx.memory.write::<{typ}>({addr}, {expr});")
}

impl<'a> CodeGen<'a> {
    pub fn get_op(&self, instr: &iced_x86::Instruction, n: u32) -> String {
        use iced_x86::OpKind::*;
        match instr.op_kind(n) {
            Immediate8 => format!("{:#x}u8", instr.immediate8()),
            Immediate16 => format!("{:#x}u16", instr.immediate16()),
            Immediate8to16 => format!("{:#x}u16", instr.immediate8to16()),
            Immediate8to32 => format!("{:#x}u32", instr.immediate8to32()),
            Immediate32 => format!("{:#x}u32", instr.immediate32()),
            Register => get_reg(instr.op_register(n)),
            Memory => get_mem(format!("u{}", mem_size(instr)), self.gen_addr(instr)),
            k => todo!("{:?}", k),
        }
    }
}

pub fn reg_size(r: iced_x86::Register) -> usize {
    use iced_x86::Register::*;
    match r {
        AL | AH | BL | BH | CL | CH | DL | DH => 8,
        AX | BX | CX | DX | SI | DI | BP | SP => 16,
        CS | DS | ES | FS | GS | SS => 16,
        EAX | EBX | ECX | EDX | ESI | EDI | ESP | EBP => 32,
        MM0 | MM1 | MM2 | MM3 | MM4 | MM5 | MM6 | MM7 => 64,
        r => todo!("{r:?}"),
    }
}

pub fn mem_size(instr: &iced_x86::Instruction) -> usize {
    use iced_x86::MemorySize::*;
    match instr.memory_size() {
        UInt8 | Int8 => 8,
        UInt16 | Int16 => 16,
        UInt32 | Int32 => 32,
        UInt64 | Int64 => 64,
        Float32 => 32,
        Float64 => 64,
        Float80 => 80,
        Packed32_UInt8 => 32,
        Packed64_Int8 | Packed64_Int16 => 64,
        DwordOffset => 32, // e.g. `call dword ptr [...]`
        s => todo!("{s:?}"),
    }
}

pub fn op_size(instr: &iced_x86::Instruction, n: u32) -> usize {
    use iced_x86::OpKind::*;
    match instr.op_kind(n) {
        Register => reg_size(instr.op_register(n)),
        Memory => mem_size(instr),
        Immediate16 => 16,
        Immediate8to16 => 16,
        Immediate8to32 => 32,
        Immediate32 => 32,
        k => todo!("{k:?}"),
    }
}

impl<'a> CodeGen<'a> {
    pub fn set_op(&self, instr: &iced_x86::Instruction, n: u32, expr: String) -> String {
        use iced_x86::OpKind::*;
        match instr.op_kind(n) {
            Register => set_reg(instr.op_register(n), expr),
            Memory => {
                let addr = self.gen_addr(instr);
                let size = mem_size(instr);
                set_mem(format!("u{size}"), addr, expr)
            }
            k => todo!("{:?}", k),
        }
    }
}

pub struct CodeGen<'a> {
    module: &'a Module,
    mem: &'a Memory,
    blocks: &'a HashMap<u32, Block>,
    trace: bool,
    /// Statically-known jump targets with no discovered block; each gets a
    /// panicking stub function so the output still compiles and runs.
    unknown: std::collections::BTreeSet<u32>,
    /// Output buffer.
    buf: String,
}

impl<'a> CodeGen<'a> {
    pub fn new(state: &'a State, trace: bool) -> Self {
        Self {
            module: &state.module,
            mem: &state.mem,
            blocks: &state.blocks,
            trace,
            unknown: Default::default(),
            buf: Default::default(),
        }
    }

    fn line(&mut self, s: impl AsRef<str>) {
        self.buf.push_str(s.as_ref());
        self.buf.push('\n');
    }

    /// Codegen a Cont expression for a jump to a statically known address.
    /// Safe to evaluate in argument position: an unknown target resolves to a
    /// stub that only panics once actually jumped to.
    pub fn resolve_cont(&mut self, addr: u32) -> String {
        if let Some(block) = self.blocks.get(&addr) {
            format!("Cont({})", block.name())
        } else {
            log::warn!("static jmp to unknown block {addr:08x}");
            self.unknown.insert(addr);
            format!("Cont(unk_{addr:x})")
        }
    }

    fn todo(&mut self, msg: String) {
        self.line(format!("todo!({msg:?});"));
    }

    fn gen_block(&mut self, block: &Block) {
        match &block.ty {
            BlockType::Instrs(instrs) => {
                self.line(format!(
                    "pub fn {name}(ctx: &mut Context) -> Cont {{",
                    name = block.name()
                ));
                // self.line(format!("println!(\"{name}\");", name = block.name()));
                for instr in instrs {
                    if self.trace {
                        match self.module {
                            Module::DOS(_) => {
                                self.line(format!("ctx.dump_dosbox({:#x});", instr.iced.ip32()));
                            }
                            Module::Windows(_) => todo!(),
                        }
                    }
                    if let Err(e) = self.gen_instr(instr) {
                        self.line(format!("panic!({:?});", e.to_string()));
                        break;
                    }
                }

                let last = instrs.last().unwrap();
                if last.iced.flow_control() == iced_x86::FlowControl::Next
                    || (last.iced.mnemonic() == iced_x86::Mnemonic::Call && last.hint.is_some())
                {
                    let cont = self.resolve_cont(last.next_ip().to_addr());
                    self.line(cont);
                }

                self.line("}\n");
            }
            BlockType::Stdcall(_) | BlockType::Extern(_) => {
                // no emit
            }
        }
    }

    fn gen_instr(&mut self, instr: &Instr) -> anyhow::Result<()> {
        // log::info!("gen: {:08x} {}", instr.iced.ip32(), instr.iced);
        self.line(format!("// {} {}", instr.ip, instr.iced));
        if self.codegen_control_flow(instr) {
        } else if self.codegen_math(&instr.iced) {
        } else if self.codegen_string(&instr.iced) {
        } else if self.codegen_misc(&instr.iced) {
        } else if self.codegen_fpu(&instr.iced) {
        } else if self.codegen_mmx(&instr.iced) {
        } else {
            anyhow::bail!("{:?} not implemented", instr.iced.mnemonic());
        }
        Ok(())
    }

    fn gen_init(&mut self) {
        // It would be cool if we could just link a wasm object file that contains data sections
        // like
        //   (data (i32.const 0x400000) "....")
        // Unfortunately, wasm-lld only supports "relocatable" object files which means it moves
        // the location of such data at link time.  We could do it by postprocessing the wasm
        // file, maybe.

        self.line("fn init(regs: &mut runtime::Regs, memory: &mut runtime::Memory, mappings: &mut runtime::Mappings) {");

        for map in self.mem.mappings.vec().iter() {
            let addr = map.addr;
            let buf = self.mem.slice(map.addr, map.size);
            let zeroed = buf.iter().all(|&b| b == 0);

            self.line(format!(
                "mappings.reserve(runtime::Mapping {{
                    desc: {desc:?}.to_string(),
                    addr: {addr:#x},
                    size: {size:#x},
                    section: {section},
                }});",
                desc = map.desc,
                size = buf.len(),
                section = map.section,
            ));
            if !zeroed {
                self.line(format!(
                    "let bytes = include_bytes!(\"../data/{addr:08x}.raw\").as_slice();
let out = &mut memory.bytes[{addr:#x}..][..bytes.len()];
out.copy_from_slice(bytes);",
                ));
            }
        }

        match self.module {
            Module::Windows(module) => {
                if !module.vtables.is_empty() {
                    self.line("unsafe {");
                    for (module, val) in &module.vtables {
                        self.line(format!("winapi::{module}::VTABLE = {val:#x};"));
                    }
                    self.line("}");
                }
                for (dll, func) in &module.dynamic_exports {
                    let addr = module
                        .imports
                        .iter()
                        .find(|imp| imp.dll == *dll && imp.func == *func)
                        .expect("dynamic export without a reserved address")
                        .addr;
                    self.line(format!(
                        "winapi::kernel32::register_export({dll:?}, {func:?}, {addr:#x});"
                    ));
                }
            }
            Module::DOS(module) => {
                self.line(format!("
regs.cs = {load_segment:#x};
regs.ds = {psp_segment:#x}; // PSP
regs.es = {psp_segment:#x}; // PSP
regs.ss = {stack_segment:#x};
// initial cx: https://stackoverflow.com/questions/79440940/why-cx-register-already-has-a-non-zero-value-on-startup-of-a-dos-program-unlike
regs.ecx = 0xff;
regs.esp = {stack_pointer:#x};
",
                    load_segment = module.load_segment,
                    psp_segment = module.psp_segment,
                    stack_segment = module.stack_segment,
                    stack_pointer = module.stack_pointer,
                ));
                if module.is_com {
                    self.line("regs.esp = 0xfffe;");
                } else {
                    self.line(format!(
                        "regs.edx = {:#x}; // PSP segment",
                        module.psp_segment
                    ));

                    self.line(
                        "
                        // arbitrary values, matching dosbox
                        regs.esi = 0x68e;
                        regs.edi = 0x800;
                        regs.ebp = 0x91c;
                        ",
                    );
                }
            }
        }

        self.line("}");
        self.line("");
    }

    /// Emit the block functions, split across `generated/part_NN.rs` files
    /// once there are enough of them.
    ///
    /// rustc's time on one module grows worse than linearly, and a large
    /// program's blocks would otherwise land in a single ten-megabyte file that
    /// has to be reparsed in full on every rebuild. Returns the part names, or
    /// an empty list when everything fit in the module file itself.
    fn gen_blocks(&mut self, outdir: &str) -> Result<Vec<String>> {
        /// Split once a part reaches roughly this size. Small programs stay in
        /// a single file, which keeps their generated output easy to read.
        /// Stay under 1mb because that is the largest size Jujutsu wants to track.
        const MAX_PART_BYTES: usize = 512 << 10;

        let mut addrs = self.blocks.keys().copied().collect::<Vec<_>>();
        addrs.sort();

        // Generate every block into one buffer first, remembering where each
        // one starts so parts can be cut at function boundaries.
        let module_buf = std::mem::take(&mut self.buf);
        let mut boundaries = vec![0usize];
        for &addr in &addrs {
            let block = self.blocks.get(&addr).unwrap();
            self.gen_block(&block);
            boundaries.push(self.buf.len());
        }
        for addr in self.unknown.iter().copied().collect::<Vec<_>>() {
            self.line(format!(
                "pub fn unk_{addr:x}(_ctx: &mut Context) -> Cont {{
    runtime::unknown_block({addr:#x})
}}\n"
            ));
            boundaries.push(self.buf.len());
        }
        let blocks_text = std::mem::replace(&mut self.buf, module_buf);

        if blocks_text.len() <= MAX_PART_BYTES {
            self.buf.push_str(&blocks_text);
            self.gen_blocks_table(&addrs);
            return Ok(Vec::new());
        }

        // Cut at the first block boundary past each part's size limit.
        std::fs::create_dir_all(format!("{outdir}/src/generated"))?;
        let mut parts = Vec::new();
        let mut start = 0;
        while start < blocks_text.len() {
            let target = start + MAX_PART_BYTES;
            let end = match boundaries.iter().find(|&&b| b >= target) {
                Some(&end) => end,
                None => blocks_text.len(),
            };
            let name = format!("part_{:02}", parts.len());
            let path = format!("{outdir}/src/generated/{name}.rs");
            let text = format!("{}\n{}", PART_HEADER, &blocks_text[start..end]);
            write_if_changed(&path, rustfmt(&text)?.as_bytes())
                .map_err(|err| anyhow!("write {path}: {err}"))?;
            parts.push(name);
            start = end;
        }

        for name in &parts {
            self.line(format!("mod {name};"));
            self.line(format!("pub use {name}::*;"));
        }
        self.line("");
        self.gen_blocks_table(&addrs);
        Ok(parts)
    }

    fn gen_blocks_table(&mut self, addrs: &[u32]) {
        self.line(format!(
            "const BLOCKS: [(u32, ContFn); {}] = [\n",
            addrs.len() + 1,
        ));

        for &addr in addrs {
            let block = self.blocks.get(&addr).unwrap();
            self.line(format!("({addr:#x}, {name}),", name = block.name()));
        }
        match self.module {
            Module::Windows(_) => {
                self.line("(runtime::RETURN_FROM_X86_ADDR32, Context::return_from_x86),");
            }
            Module::DOS(_) => {
                self.line("(runtime::RETURN_FROM_X86_ADDR16.abs(), Context::return_from_x86),");
            }
        }
        self.line("];");
        self.line("");
    }

    pub fn gen_file(&mut self, outdir: &str) -> Result<()> {
        self.line(HEADER);
        if self.module.is_windows() {
            self.line("use winapi::*;");
        }

        self.gen_init();

        let parts = self.gen_blocks(outdir)?;

        // TODO: split EXEDATA into DOS/Windows.
        let resources = match self.module {
            Module::DOS(_) => 0..0,
            Module::Windows(m) => m.resources.clone().unwrap_or(0..0),
        };

        let entry_point = self.module.entry_point().to_addr();
        let entry_point = self
            .blocks
            .get(&entry_point)
            .ok_or_else(|| anyhow!("entry point {entry_point:x} not found in parsed blocks"))?;
        self.line(format!(
            "pub const EXEDATA: EXEData = EXEData {{
            image_base: {image_base:#x},
            resources: {res_start:#x}..{res_end:#x},
            blocks: &BLOCKS,
            init,
            entry_point: Cont({entry_point}),
        }};\n\n",
            image_base = self.module.image_base(),
            res_start = resources.start,
            res_end = resources.end,
            entry_point = entry_point.name(),
        ));

        std::fs::create_dir_all(format!("{outdir}/src"))?;
        let path = format!("{outdir}/src/generated.rs");
        let text = rustfmt(&self.buf)?;
        write_if_changed(&path, text.as_bytes()).map_err(|err| anyhow!("write {path}: {err}"))?;

        // Drop parts left over from a previous run that produced more of them,
        // which would otherwise fail to compile against the current output.
        if let Ok(entries) = std::fs::read_dir(format!("{outdir}/src/generated")) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                let Some(stem) = name.strip_suffix(".rs") else {
                    continue;
                };
                if stem.starts_with("part_") && !parts.iter().any(|part| part == stem) {
                    std::fs::remove_file(entry.path())?;
                }
            }
        }
        Ok(())
    }
}

fn rustfmt(text: &str) -> Result<String> {
    use std::io::Write;
    // Stolen from https://github.com/microsoft/windows-rs/blob/master/crates/tools/lib/src/lib.rs
    let mut child = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()?;
    let mut stdin = child.stdin.take().unwrap();
    stdin.write_all(text.as_bytes())?;
    drop(stdin);
    let output = child.wait_with_output()?;

    if !output.status.success() {
        bail!("rustfmt failed: {}", std::str::from_utf8(&output.stderr)?);
    }
    Ok(String::from_utf8(output.stdout)?)
}
